server:
  port: '8083'
  servlet:
    session:
      timeout: 1800
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/T_WEB #local
    username: root
    password: root
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
#      location: C:\WORKSPACE\ATTACH  # WINDOW
      location : /Users/taewoohan/WorkFolder/WORKSPACE_ATTACH/T_WEB/ # MAC
      max-file-size: 100MB
      max-request-size: 500MB

logging:
  config: classpath:log4j2.xml
  level:
    com.demo.t_web: DEBUG

naver:
  apiKeyId: qf1nz5j1ox
  apiKey: zKk2iApYsA7XFiXgqTTdtguAsvgSJlXZJ59a1HhL
  drivingUrl: https://naveropenapi.apigw.ntruss.com/map-direction/v1/driving
  clientId: SZsefxLD_WiBWtIpAEh0
  clientSecret: jOPI3V1JOF
