name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        working-directory: ./frontend
        run: |
          npm ci
          CI='false' npm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: adp
          folder: ./frontend/build/
          repository-name: tarr4h/adp
          clean: true
          token: ${{ secrets.TOKEN }}